### ISSUE TITLE
Image task not copying some images over to dist?

### ISSUE THREAD

**Issue by Bluematter** [google/web-starter-kit#579]
I have been struggling with gulp-imagemin for the past few days, one it will not compress the images, I am basing that off the images being the same file size and page speed insights telling me to compress them, this is not a big deal as I don't use many images and can manually compress them, just thought I would mention this.

The thing that gets me is why certain images are not being copied over into the dist build. This has happened to me on numerous occasions over the past few days. I tried clearing the gulp-cache 

    gulp.task('clear', function (done) {
      return $.cache.clearAll(done);
    });

I am not sure what else I can add, I doubt this is enough to help troubleshoot, but has anyone else experienced this, perhaps I am doing something wrong?

**Comment by addyosmani** [comment]
Thanks for posting back about the caching issues you ran into. You shouldn't have to disable `$.cache` in this way, but we'll investigate and see if we can repro.

**Comment by ithinkihaveacat** [comment]
@Bluematter Long shot, but are all your images in the in the `app/images` directory? Images in other directories will be served by `gulp serve`, but they won't become part of the static `dist` build. (Something [like this](https://github.com/ithinkihaveacat/web-starter-kit/commit/9a5c22fa65d270e0b4b8a067f8b2e31987ec73cb) might help make them work; this doesn't explain the interaction with caching though…)

**Comment by addyosmani** [comment]
I haven't been able to reproduce this issue. Is anyone else running into this issue with gulp-cache? I've been reading up on https://github.com/jgable/gulp-cache/issues/16 but that issue is closed.

**Comment by akullpp** [comment]
Encountered the same issue in combination with Jenkins, same setup as described above.

**Comment by webwelten** [comment]
Same problem here.
Have the images in app/images as well and not using $.cache makes it work.

**Comment by webwelten** [comment]
What helped in my case was [clearing the cache](https://github.com/jgable/gulp-cache#clearing-the-cache). Once I did that I've had no more problems. Does this also help someone else?

**Comment by hugohcn** [comment]
Hey Guys,

I have the same problem here. Looking for a solution, I tried this code and it worked:

```javascript
// Optimize Images
gulp.task('images', function () {
  return gulp.src('app/images/**/*.{gif,jpg,png,svg}')
    .pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true,
      pngquant: true
    })))
    .pipe(gulp.dest('dist/images'))
    .pipe($.size({title: 'images'}));
});
```

**Comment by pavangupta** [comment]
Hola.  Looks like the gulp.src function was sending along base directories (e.g., app/images/icon) and this was causing a freshly tightened gulp-cache to choke on generating a key for a file that it could not understand.  Using gulp-if and it's direct relationship with gulp-match, you can comfortably drop out the base directories from the image optimization pipeline before you run into problems.  This is a bit of an annoying problem (globs suck, the gulp-cache plugin needs friends, and it looks like a lot of people hack their way around this problem), but I bet this kind of pattern feels right -- you're checking to see if you're reviewing a file before you start trying to process a file.  Poke me with questions!  Hope this helps!

**Comment by hugohcn** [comment]
@pavangupta nice! thks.

**Comment by pavangupta** [comment]
:), happy to help!

**Comment by shinnn** [comment]
Fixed in https://github.com/jgable/gulp-cache/pull/43.

**Comment by shinnn** [comment]
@pavangupta You can close both this and #636.

**Comment by pavangupta** [comment]
@shinnn you guys are awesome!  pull requests closed!

**Comment by neilmonroe** [comment]
Thanks for fixing this! I was still having the issue even after upgrading all of the node dependencies. The key was what @webwelten suggested. You have to clear the cache to get rid of bad entries or else you will still get the missing files in your dist build.

**Comment by stevemao** [comment]
This can also be closed :)

**Comment by nicolasgarnier** [comment]
Closing! :D

**Comment by NicolasRannou** [comment]
Doesn't seem to work after pulling master today...
